"""Public package exports for the qdrant-odm library."""

from qdrant_odm.client import QdrantODM
from qdrant_odm.exceptions import (
    ModelDefinitionError,
    NotFoundError,
    QdrantODMError,
    QueryCompileError,
    RepositoryError,
    SchemaConflictError,
    SerializationError,
)
from qdrant_odm.model import (
    BoolIndexOptions,
    CollectionConfig,
    CollectionModeLiteral,
    DatetimeIndexOptions,
    DistanceLiteral,
    FloatIndexOptions,
    GeoIndexOptions,
    IntegerIndexOptions,
    KeywordIndexOptions,
    ModelMetadata,
    PayloadField,
    PayloadFieldInfo,
    QdrantModel,
    SparseVectorField,
    SparseVectorFieldInfo,
    TextIndexOptions,
    TokenizerLiteral,
    UuidIndexOptions,
    VectorField,
    VectorFieldInfo,
    clear_registry,
    get_model,
    model_from_point,
    model_to_payload,
    register_model,
)
from qdrant_odm.query import (
    ComparisonExpr,
    Expr,
    FieldExpr,
    FilterCompiler,
    FilterExpression,
    HybridSearchQuery,
    LogicalExpr,
    NotExpr,
    SearchQuery,
    SparseVectorInput,
)
from qdrant_odm.repository import (
    DEFAULT_RETRIEVE_CHUNK_SIZE,
    DEFAULT_UPSERT_BATCH_SIZE,
    QdrantRepository,
    SearchHit,
)
from qdrant_odm.schema import (
    SchemaDiff,
    SchemaManager,
    SchemaOperation,
    build_sync_operations,
    compute_schema_diff,
)
from qdrant_odm.types import ScrollPage
from qdrant_odm.utils.chunking import chunked
from qdrant_odm.transaction import Transaction

__all__ = [
    "BoolIndexOptions",
    "CollectionConfig",
    "CollectionModeLiteral",
    "ComparisonExpr",
    "DEFAULT_RETRIEVE_CHUNK_SIZE",
    "DEFAULT_UPSERT_BATCH_SIZE",
    "DatetimeIndexOptions",
    "DistanceLiteral",
    "Expr",
    "FieldExpr",
    "FilterCompiler",
    "FilterExpression",
    "FloatIndexOptions",
    "GeoIndexOptions",
    "HybridSearchQuery",
    "IntegerIndexOptions",
    "KeywordIndexOptions",
    "LogicalExpr",
    "ModelDefinitionError",
    "ModelMetadata",
    "NotExpr",
    "NotFoundError",
    "PayloadField",
    "PayloadFieldInfo",
    "QdrantODM",
    "QdrantModel",
    "QdrantODMError",
    "QdrantRepository",
    "QueryCompileError",
    "RepositoryError",
    "SchemaConflictError",
    "SchemaDiff",
    "SchemaManager",
    "SchemaOperation",
    "ScrollPage",
    "SearchHit",
    "SearchQuery",
    "SerializationError",
    "SparseVectorField",
    "SparseVectorFieldInfo",
    "SparseVectorInput",
    "TextIndexOptions",
    "TokenizerLiteral",
    "Transaction",
    "UuidIndexOptions",
    "VectorField",
    "VectorFieldInfo",
    "build_sync_operations",
    "chunked",
    "clear_registry",
    "compute_schema_diff",
    "get_model",
    "model_from_point",
    "model_to_payload",
    "register_model",
]