"""Named filter operators for documentation and future tooling."""

OP_EQ = "eq"
OP_NE = "ne"
OP_GT = "gt"
OP_GTE = "gte"
OP_LT = "lt"
OP_LTE = "lte"
OP_IN = "in"
OP_NOT_IN = "not_in"
OP_IS_NULL = "is_null"
OP_IS_NOT_NULL = "is_not_null"
OP_AND = "and"
OP_OR = "or"
OP_NOT = "not"
